package br.gov.siscomex.portalunico.duimp_balanca_itens.api;

import br.gov.siscomex.portalunico.duimp_balanca_itens.model.DuimpItemBalancaComercialCover;
import br.gov.siscomex.portalunico.duimp_balanca_itens.model.RespostaApiErro;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

import javax.validation.constraints.NotNull;
import javax.ws.rs.DefaultValue;
import javax.ws.rs.GET;
import javax.ws.rs.HeaderParam;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Response;

/**
 * Declaração Única de Importação - Balança Comercial - Itens de Duimp
 *
 * <p>No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 */
@Path("/")
@Api(value = "/", description = "")
public interface DuimpDadosDeItensApi {

    /**
     * Recupera as informações dos Dados de itens das Duimps solicitadas como parâmetros.
     */
    @GET
    @Path("/duimp/itens")
    @Produces({"application/json"})
    @ApiOperation(value = "Recupera as informações dos Dados de itens das Duimps solicitadas como parâmetros.", notes = "", tags = {"Duimp - Dados de Itens"})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Operação realizada com sucesso", response = DuimpItemBalancaComercialCover.class, responseContainer = "List"),
            @ApiResponse(code = 206, message = "Resultado parcial. Utilize o mecanismo de paginação para recuperar mais dados", response = DuimpItemBalancaComercialCover.class, responseContainer = "List"),
            @ApiResponse(code = 401, message = "Usuário não autenticado ou autenticação inválida", response = RespostaApiErro.class),
            @ApiResponse(code = 403, message = "Usuário não tem permissão de acesso ao recurso", response = RespostaApiErro.class),
            @ApiResponse(code = 404, message = "Recurso não encontrado", response = RespostaApiErro.class),
            @ApiResponse(code = 422, message = "Erro(s) de validação da camada de negócio", response = RespostaApiErro.class),
            @ApiResponse(code = 500, message = "Erro interno no servidor", response = RespostaApiErro.class)})
    Response obterDadosItensV2UsingGET(@ApiParam(value = "JSON Web Token (JWT) contendo as informações do usuário.<br>Este token é recuperado no parâmetro Set-Token no response da autenticação", required = true) @HeaderParam("Authorization") String authorization, @ApiParam(value = "Token de prevenção contra ataques CSRF. <br>Este token é recuperado no parâmetro X-CSRF-Token no response da autenticação", required = true) @HeaderParam("X-CSRF-Token") String xCSRFToken, @NotNull @ApiParam(value = "Identificador único da consulta. <br>O valor deste parâmetro é recuperado no header da primeira página da consulta dos dados gerais.<br>Este atributo é obrigatório para recuperar os dados dos itens", required = true) @QueryParam("id-consulta") String idConsulta, @ApiParam(value = "Tamanho limite da quantidade de dados retornados.<br>Formato: Inteiro, com até 10 dígitos", defaultValue = "1000") @DefaultValue("1000") @QueryParam("limit") Integer limit, @ApiParam(value = "Índice do primeiro elemento.<br>Formato: Inteiro, com até 10 dígitos", defaultValue = "0") @DefaultValue("0") @QueryParam("offset") Integer offset);
}

